// This file is auto-generated by TanStack Router
import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRoute } from './routes/dashboard'
import { Route as IndexRoute } from './routes/index'
import { Route as LoginRoute } from './routes/login'
import { Route as ProfileRoute } from './routes/profile'
import { Route as SignupRoute } from './routes/signup'

const SignupRouteWithChildren = SignupRoute
const ProfileRouteWithChildren = ProfileRoute
const LoginRouteWithChildren = LoginRoute
const DashboardRouteWithChildren = DashboardRoute
const IndexRouteWithChildren = IndexRoute

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupRouteWithChildren
      parentRoute: typeof rootRoute
    }
  }
}

Object.assign(IndexRoute.options, {
  path: '/',
  getParentRoute: () => rootRoute,
})

Object.assign(DashboardRoute.options, {
  path: '/dashboard',
  getParentRoute: () => rootRoute,
})

Object.assign(LoginRoute.options, {
  path: '/login',
  getParentRoute: () => rootRoute,
})

Object.assign(ProfileRoute.options, {
  path: '/profile',
  getParentRoute: () => rootRoute,
})

Object.assign(SignupRoute.options, {
  path: '/signup',
  getParentRoute: () => rootRoute,
})

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DashboardRoute,
  LoginRoute,
  ProfileRoute,
  SignupRoute,
])
